__app__ = 'WorkBreakTimer'
__display__ = 'Work/Break Timer'
__version__ = '0.3.0'
__repo__ = 'https://github.com/AlexCovizzi/WorkBreakTimer'
__issues__ = 'https://github.com/AlexCovizzi/WorkBreakTimer/issues'
