name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x86
    - name: Set up environment
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install dependencies
      run: |
        pipenv run install
        pipenv run install --dev
    - name: Test
      run: |
        pipenv run test
    - name: Package
      run: |
        pipenv run pyinstaller app.spec
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: WorkBreakTimer
        path: dist/WorkBreakTimer.exe
